#!/usr/bin/env python3
"""Generate hashed pip requirements from curated exact pins (PyPI JSON only).

Run from a networked host after deliberate pin bumps:
  python gateway/python/generate-locks.py

Does not install packages; fetches metadata/hashes from https://pypi.org only.
"""
from __future__ import annotations

import json
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent
PYPI = "https://pypi.org/pypi"


def pypi_project(name: str, version: str | None = None) -> dict:
    url = f"{PYPI}/{name}/{version}/json" if version else f"{PYPI}/{name}/json"
    with urllib.request.urlopen(url, timeout=60) as resp:
        return json.load(resp)


def hashes_for(name: str, version: str) -> list[str]:
    data = pypi_project(name, version)
    out: list[str] = []
    seen: set[str] = set()
    for item in data.get("urls", []):
        sha = (item.get("digests") or {}).get("sha256")
        if sha and sha not in seen:
            seen.add(sha)
            out.append(f"    --hash=sha256:{sha}")
    if not out:
        raise SystemExit(f"no hashes for {name}=={version}")
    return out


def write_requirements(path: pathlib.Path, pins: list[tuple[str, str]], header: str) -> None:
    lines = [header.rstrip(), ""]
    for name, version in pins:
        print(f"hash {name}=={version}", file=sys.stderr)
        lines.append(f"{name}=={version}")
        lines.extend(hashes_for(name, version))
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {path}", file=sys.stderr)


# Pins chosen inside mitmproxy 12.2.3 declared upper bounds (see pypi requires_dist).
MITM_PINS: list[tuple[str, str]] = [
    ("mitmproxy", "12.2.3"),
    ("aioquic", "1.2.0"),
    ("argon2-cffi", "25.1.0"),
    ("argon2-cffi-bindings", "25.1.0"),
    ("asgiref", "3.11.1"),
    ("attrs", "25.3.0"),
    ("bcrypt", "5.0.0"),
    ("blinker", "1.9.0"),
    ("Brotli", "1.2.0"),
    ("certifi", "2026.1.4"),
    ("cffi", "1.17.1"),
    ("click", "8.1.8"),
    ("cryptography", "44.0.2"),
    ("Flask", "3.1.3"),
    ("h11", "0.16.0"),
    ("h2", "4.3.0"),
    ("hpack", "4.1.0"),
    ("hyperframe", "6.1.0"),
    ("itsdangerous", "2.2.0"),
    ("Jinja2", "3.1.6"),
    ("kaitaistruct", "0.11"),
    ("ldap3", "2.9.1"),
    ("MarkupSafe", "3.0.2"),
    ("mitmproxy-rs", "0.12.7"),
    ("mitmproxy-linux", "0.12.7"),
    ("msgpack", "1.1.1"),
    ("pyasn1", "0.6.1"),
    ("pyasn1-modules", "0.4.2"),
    ("pycparser", "2.22"),
    ("pylsqpack", "0.3.22"),
    ("pyOpenSSL", "25.1.0"),
    ("pyparsing", "3.2.3"),
    ("pyperclip", "1.9.0"),
    ("publicsuffix2", "2.20191221"),
    ("ruamel.yaml", "0.18.10"),
    ("ruamel.yaml.clib", "0.2.12"),
    ("service-identity", "24.2.0"),
    ("sortedcontainers", "2.4.0"),
    ("tornado", "6.5.1"),
    ("typing-extensions", "4.13.2"),
    ("urwid", "2.6.16"),
    ("wcwidth", "0.2.13"),
    ("Werkzeug", "3.1.3"),
    ("wsproto", "1.2.0"),
    ("zstandard", "0.25.0"),
]

# FakeNet runtime deps used by install-fakenet.sh (exact). FakeNet itself is a
# separate GitHub zip pinned in fakenet-source.pin (not a PyPI wheel).
FAKENET_PINS: list[tuple[str, str]] = [
    ("NetfilterQueue", "1.1.0"),
    ("dnslib", "0.9.26"),
    ("dpkt", "1.9.8"),
    ("pyOpenSSL", "25.1.0"),
    ("cryptography", "44.0.2"),
    ("pyftpdlib", "2.0.1"),
    ("pyasyncore", "1.0.4"),
    ("pyasynchat", "1.0.4"),
    ("netifaces", "0.11.0"),
    ("Jinja2", "3.1.6"),
    ("MarkupSafe", "3.0.2"),
    ("cffi", "1.17.1"),
    ("pycparser", "2.22"),
    ("typing-extensions", "4.13.2"),
]


def main() -> None:
    write_requirements(
        ROOT / "requirements-mitm.txt",
        MITM_PINS,
        "# Locked mitmproxy stack for quarantine gateway.\n"
        "# Regenerated by: python gateway/python/generate-locks.py\n"
        "# Install: pip install --require-hashes --prefer-binary -r requirements-mitm.txt",
    )
    write_requirements(
        ROOT / "requirements-fakenet.txt",
        FAKENET_PINS,
        "# Locked FakeNet-NG dependency stack (FakeNet source is fakenet-source.pin).\n"
        "# Regenerated by: python gateway/python/generate-locks.py\n"
        "# Install: pip install --require-hashes --prefer-binary -r requirements-fakenet.txt",
    )


if __name__ == "__main__":
    main()
