#!/bin/bash
# Quarantine Gateway first-boot / provision script.
# Idempotent: safe to re-run. Expects Debian/Ubuntu with systemd.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPT=/opt/quarantine-gateway
LOG=/var/log/quarantine
LAN_CIDR="${QUARANTINE_LAN_CIDR:-10.66.0.0/24}"
LAN_IP="${QUARANTINE_LAN_GATEWAY:-10.66.0.1}"
GUEST_IP="${QUARANTINE_GUEST_IP:-10.66.0.15}"
AGENT_PORT="${QUARANTINE_AGENT_PORT:-9443}"
LAN_IF="${QUARANTINE_LAN_IF:-}"
WAN_IF="${QUARANTINE_WAN_IF:-}"

mkdir -p "$OPT" "$LOG/pcap" "$LOG/proxy" /etc/quarantine-gateway
cp -a "$ROOT/." "$OPT/"

export DEBIAN_FRONTEND=noninteractive

# Detect interfaces: prefer eth0/enp0s3 as WAN (NAT), eth1/enp0s8 as LAN (intnet)
detect_ifaces() {
  local -a ifs=()
  while read -r name; do
    [[ "$name" == "lo" ]] && continue
    ifs+=("$name")
  done < <(ls /sys/class/net | sort)
  if [[ -z "$WAN_IF" && ${#ifs[@]} -ge 1 ]]; then WAN_IF="${ifs[0]}"; fi
  if [[ -z "$LAN_IF" && ${#ifs[@]} -ge 2 ]]; then LAN_IF="${ifs[1]}"; fi
  if [[ -z "$LAN_IF" ]]; then LAN_IF="${WAN_IF:-eth0}"; fi
  if [[ -z "$WAN_IF" ]]; then WAN_IF=eth0; fi
}
detect_ifaces

echo "WAN=$WAN_IF" >/etc/quarantine-gateway/ifaces.env
echo "LAN=$LAN_IF" >>/etc/quarantine-gateway/ifaces.env
echo "LAN_IF=$LAN_IF" >>/etc/quarantine-gateway/ifaces.env
echo "LAN_IP=$LAN_IP" >>/etc/quarantine-gateway/ifaces.env
echo "WAN=$WAN_IF LAN=$LAN_IF LAN_IP=$LAN_IP"

# WAN DNS via VirtualBox NAT (10.0.2.3) — do this before apt/pip
fix_wan_dns() {
  # Free UDP/TCP 53 on loopback for dnsmasq later; host DNS still works via NAT
  mkdir -p /etc/systemd/resolved.conf.d
  cat >/etc/systemd/resolved.conf.d/disable-stub.conf <<EOF
[Resolve]
DNSStubListener=no
EOF
  # Never put public DNS nameservers on the LAN (intnet) — resolved will
  # mark that link DefaultRoute and break WAN name resolution.
  if command -v netplan >/dev/null 2>&1 && [[ -d /etc/netplan ]]; then
    cat >/etc/netplan/99-quarantine-lan.yaml <<EOF
network:
  version: 2
  ethernets:
    ${LAN_IF}:
      dhcp4: false
      addresses: [${LAN_IP}/24]
      optional: true
EOF
    if [[ "$WAN_IF" != "$LAN_IF" ]]; then
      cat >/etc/netplan/98-quarantine-wan.yaml <<EOF
network:
  version: 2
  ethernets:
    ${WAN_IF}:
      dhcp4: true
      nameservers:
        addresses: [10.0.2.3, 1.1.1.1, 8.8.8.8]
EOF
    fi
    chmod 600 /etc/netplan/99-quarantine-lan.yaml /etc/netplan/98-quarantine-wan.yaml 2>/dev/null || true
    netplan apply || true
  fi
  ip link set "$LAN_IF" up || true
  if ! ip -4 addr show dev "$LAN_IF" | grep -q " ${LAN_IP}/"; then
    ip addr add "${LAN_IP}/24" dev "$LAN_IF" 2>/dev/null || true
  fi
  # Static resolv.conf — VBox NAT DNS first
  rm -f /etc/resolv.conf
  printf 'nameserver 10.0.2.3\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n' >/etc/resolv.conf
  systemctl restart systemd-resolved 2>/dev/null || true
  # resolved may rewrite resolv.conf; pin it again if stub returns
  if [[ -L /etc/resolv.conf ]] || grep -q '127.0.0.53' /etc/resolv.conf 2>/dev/null; then
    rm -f /etc/resolv.conf
    printf 'nameserver 10.0.2.3\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n' >/etc/resolv.conf
  fi
}
fix_wan_dns

# Ensure WAN has a lease before apt (Ubuntu 26+ has no dhclient by default)
ip link set "$WAN_IF" up || true
if command -v networkctl >/dev/null 2>&1; then
  networkctl renew "$WAN_IF" 2>/dev/null || networkctl reconfigure "$WAN_IF" 2>/dev/null || true
fi
sleep 2

apt-get update -y || true
# Core packages (fail hard if these cannot install)
apt-get install -y --no-install-recommends \
  nftables dnsmasq tcpdump python3 python3-pip python3-venv \
  iptables ca-certificates curl openssl net-tools iproute2
# Build headers only if mirrors work — mitmproxy 12 prefers binary wheels
apt-get install -y --no-install-recommends \
  python3-dev build-essential libffi-dev || true

# IP forwarding
cat >/etc/sysctl.d/99-quarantine-gateway.conf <<EOF
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=0
EOF
sysctl --system >/dev/null || sysctl -w net.ipv4.ip_forward=1

# dnsmasq — bind only LAN gateway address (LAN clients only; WAN uses 10.0.2.3)
mkdir -p "$LOG"
cat >/etc/dnsmasq.d/quarantine-gateway.conf <<EOF
# Generated by first-boot.sh — LAN DNS/DHCP for quarantine-net
interface=${LAN_IF}
bind-interfaces
except-interface=lo
except-interface=${WAN_IF}
domain-needed
bogus-priv
no-resolv
server=10.0.2.3
server=1.1.1.1
server=8.8.8.8
listen-address=${LAN_IP}
dhcp-range=10.66.0.50,10.66.0.200,12h
dhcp-option=option:router,${LAN_IP}
dhcp-option=option:dns-server,${LAN_IP}
dhcp-host=lab-guest,10.66.0.15
log-queries
log-facility=${LOG}/dnsmasq.log
EOF
# Packaged defaults: avoid listening on all interfaces
if [[ -f /etc/dnsmasq.conf ]]; then
  sed -i 's/^#\?bind-interfaces.*/bind-interfaces/' /etc/dnsmasq.conf || true
fi
systemctl enable dnsmasq
systemctl restart dnsmasq

# Re-assert WAN DNS after dnsmasq (do not let LAN steal default DNS)
fix_wan_dns
# Keep LAN address after netplan re-apply
if ! ip -4 addr show dev "$LAN_IF" | grep -q " ${LAN_IP}/"; then
  ip addr add "${LAN_IP}/24" dev "$LAN_IF" 2>/dev/null || true
fi
systemctl restart dnsmasq || true

# nftables — substitute interface names
sed -e "s/__WAN__/${WAN_IF}/g" -e "s/__LAN__/${LAN_IF}/g" -e "s|__LAN_CIDR__|${LAN_CIDR}|g" \
  -e "s/__LAN_IP__/${LAN_IP}/g" -e "s/__GUEST_IP__/${GUEST_IP}/g" -e "s/__AGENT_PORT__/${AGENT_PORT}/g" \
  "$OPT/nftables.conf" >/etc/nftables.conf
systemctl enable nftables
systemctl restart nftables

# mitmproxy venv
# Ubuntu 26.04 ships Python 3.14; mitmproxy 11 pins deps without cp314 wheels
# (Brotli/zstandard source builds fail). Prefer mitmproxy 12+ with binary wheels.
if [[ ! -x /opt/quarantine-gateway/venv/bin/mitmdump ]]; then
  rm -rf /opt/quarantine-gateway/venv
  python3 -m venv /opt/quarantine-gateway/venv
  /opt/quarantine-gateway/venv/bin/pip install --upgrade pip setuptools wheel
  /opt/quarantine-gateway/venv/bin/pip install --prefer-binary 'mitmproxy>=12,<13'
else
  echo "mitmproxy already present — skipping pip install"
fi

# Ensure appliance files (from this script's tree) are under $OPT
test -f "$ROOT/mitm/quarantine.pac"
test -f "$ROOT/systemd/quarantine-mitm-explicit.service"
cp -a "$ROOT/." "$OPT/"

# PAC for explicit fallback (gateway LAN IP)
sed "s/__GATEWAY__/${LAN_IP}/g" "$OPT/mitm/quarantine.pac" >/etc/quarantine-gateway/quarantine.pac
cp "$OPT/mitm/block_private.py" /etc/quarantine-gateway/block_private.py
mkdir -p /usr/local/lib/quarantine
install -m 0644 "$OPT/mitm/export-flows-jsonl.py" /usr/local/lib/quarantine/export-flows-jsonl.py

install -m 0644 "$OPT/systemd/quarantine-mitm-explicit.service" /etc/systemd/system/
install -m 0644 "$OPT/systemd/quarantine-mitm-transparent.service" /etc/systemd/system/
install -m 0644 "$OPT/systemd/quarantine-capture.service" /etc/systemd/system/
install -m 0755 "$OPT/scripts/start-capture.sh" /usr/local/sbin/quarantine-capture-start
install -m 0755 "$OPT/scripts/stop-capture.sh" /usr/local/sbin/quarantine-capture-stop
install -m 0755 "$OPT/scripts/status.sh" /usr/local/sbin/quarantine-gateway-status
install -m 0755 "$OPT/scripts/sync-hint.txt" /etc/quarantine-gateway/sync-hint.txt 2>/dev/null || true

systemctl daemon-reload
systemctl enable quarantine-mitm-explicit quarantine-mitm-transparent
systemctl restart quarantine-mitm-explicit quarantine-mitm-transparent

# Export CA once mitm has run
sleep 2
CA_SRC=""
for c in /root/.mitmproxy/mitmproxy-ca-cert.pem /home/*/.mitmproxy/mitmproxy-ca-cert.pem; do
  [[ -f "$c" ]] && CA_SRC="$c" && break
done
if [[ -n "$CA_SRC" ]]; then
  openssl x509 -in "$CA_SRC" -outform DER -out /etc/quarantine-gateway/mitmproxy-ca-cert.cer 2>/dev/null \
    || cp "$CA_SRC" /etc/quarantine-gateway/mitmproxy-ca-cert.pem
  cp "$CA_SRC" /var/log/quarantine/proxy/mitmproxy-ca-cert.pem 2>/dev/null || true
  chmod 644 /etc/quarantine-gateway/mitmproxy-ca-cert.cer 2>/dev/null || true
  chmod 644 /etc/quarantine-gateway/mitmproxy-ca-cert.pem 2>/dev/null || true
fi

touch /opt/quarantine-gateway/.installed
echo "Quarantine gateway provisioned. LAN ${LAN_IP} on ${LAN_IF}, WAN ${WAN_IF}"
/usr/local/sbin/quarantine-gateway-status || true
